---
# Calistirildiginda Ansible Kurulumu Yapilir
- hosts: mys 
  remote_user: ahtapotops
  vars_files:
  - /etc/ansible/roles/ansible/vars/package.yml
  - /etc/ansible/roles/ansible/vars/ansible.yml
  - /etc/ansible/roles/ansible/vars/directory.yml
  - /etc/ansible/roles/ansible/vars/git.yml
  roles:
  - { role: ansible }
